Add timepicker
kibotu/jetpack-compose-is-like-android-view pull request #10
Opened 2022-03-16 15:01 UTC by Justus-Saringer

2022-03-16 15:17 UTC, ColdTea-Projects requested changes

2022-03-16 15:17 UTC, ColdTea-Projects commented on demo/src/main/java/de/check24/compose/demo/features/picker/ComposableTimeActivity.kt
> +                /*Scaffold(
you can remove this if you do not use anymore

2022-03-16 15:17 UTC, ColdTea-Projects commented on demo/src/main/java/de/check24/compose/demo/features/picker/ComposableTimeActivity.kt
> +    var timePicked: String by remember {
as far as I can see this value is static and does not change. Do you need to keep it as a state?

2022-03-16 15:17 UTC, ColdTea-Projects commented on code/text/Time.kt
> +        binding.timePickerTextView.text = ""
why is an empty text assigned first, then the actual text at the next line?

2022-03-16 15:58 UTC, Justus-Saringer commented on code/text/Time.kt
> +        binding.timePickerTextView.text = ""
This is a remnant of a previous thought. 😅

2022-03-16 16:17 UTC, Justus-Saringer commented on demo/src/main/java/de/check24/compose/demo/features/picker/ComposableTimeActivity.kt
> +                /*Scaffold(
Oh, I forgot to remove it, thanks :)

2022-03-21 10:10 UTC, Tautellini commented on code/text/Time.kt
> +private fun correctsTime(hour : Int, minute: Int) : String {
Is the naming optimal? How about formatTime() ?

2022-03-21 10:11 UTC, Tautellini commented on code/text/Time.xml
> +        binding.timePickerTextView.text = ""
You dont really have to empty it beforehand, do you?

2022-03-21 10:13 UTC, Justus-Saringer commented on code/text/Time.kt
> +private fun correctsTime(hour : Int, minute: Int) : String {
You are right, formatTime fits better.

2022-03-21 10:13 UTC, Justus-Saringer commented on code/text/Time.xml
> +        binding.timePickerTextView.text = ""
I thought I removed that.

2022-03-21 10:14 UTC, Tautellini commented on demo/src/main/java/de/check24/compose/demo/features/picker/AndroidUITimeActivity.kt
> +    lateinit var binding: TimeBinding
There is a reason you should always be suspicious about lateinit.

When using in Listeners and stuff, you may have still references, which makes it impossible for the garbage collector to clear it.

Its a better approach to make the binding nullable, and also clear it explicitely onDestroy so you get no leaks.
This way you have to think about a possible NullPointerException, but its something you can deal with, while you cannot with the lateinit appraoch.

2022-03-21 10:16 UTC, Tautellini commented on demo/src/main/java/de/check24/compose/demo/features/picker/AndroidUITimeActivity.kt
> +    lateinit var binding: TimeBinding
This explanation kind of gets it to the point: https://stackoverflow.com/a/70066693

2022-03-21 10:20 UTC, Tautellini commented on demo/src/main/java/de/check24/compose/demo/features/picker/ComposableTimeActivity.kt
> +    val updatedTime = { time: String ->
I prefer to write the lambdas directly where used instead of referencing it in a variable, please try to explain me what your intention here was. Do you prefer it this way?

2022-03-21 10:23 UTC, Tautellini requested changes
Check the binding part.

2022-03-21 10:29 UTC, Justus-Saringer commented on demo/src/main/java/de/check24/compose/demo/features/picker/AndroidUITimeActivity.kt
> +    lateinit var binding: TimeBinding
Thank you for the wide answer and explanation :)
I didn't know that it could create memory leaks.

2022-03-21 11:06 UTC, Justus-Saringer commented on demo/src/main/java/de/check24/compose/demo/features/picker/ComposableTimeActivity.kt
> +    val updatedTime = { time: String ->
I thought one can read it better, but you are right. It's just unnecessary code.

2022-03-21 13:49 UTC, kibotu approved these changes

2022-03-21 13:58 UTC, merged