Add toolbar and comments from knowledge-transfer
kibotu/jetpack-compose-is-like-android-view pull request #18
Opened 2022-03-24 14:28 UTC by Justus-Saringer

2022-03-25 08:58 UTC, Tautellini commented on code/button/Chip.kt
> +        color = if (isSelected) colorResource(id = R.color.purple_100) else colorResource(id = R.color.gray_300),
Do you guys have some kind of Compose Theming in the Demo App Already? Because I would just guess that this is not the most common compose way of referencing colors. 

While we decided to still use xml resources for dimens and strings, for reasons like different build flavour configurations or localization, most projects have their colors either exposed globally, or wrapped in an object. 
Normally you would try to reference MaterialTheme.colors values instead anyway, since these are the Theming handled colors.

Might make sense to include that, maybe in a different pr.

2022-03-25 09:05 UTC, Tautellini commented on code/button/ChipGroup.kt
>                  Row(
Is this still only used as a wrapper to gain a ripple effect?
You could try out setting clickable on a Box. Afaik the Ripple effect is based on those clickable modifiers, as well as the interactionSource and indication. You technically dont need to misuse Row for Ripple effects. 

I also want to do a sanity check here. Its a clickable container that changes color on selection. Could this whole thing just be one Switch (or Button)?

2022-03-25 09:07 UTC, Tautellini commented on code/button/Chip.kt
> +fun ChipExample(
I wonder, shouldnt this one be used in the ChipGroup?

2022-03-25 09:13 UTC, Tautellini commented on code/container/Toolbar.kt
> +    val expanded = remember { mutableStateOf(false) }
Try to use "by". Property delegation is a nice small feature. There is no downside in using them.

2022-03-25 09:15 UTC, Tautellini commented on code/container/Toolbar.kt
> +fun ShowOptionDropDown(expanded: MutableState<Boolean>) {
This is a common misconception. You never need to pass in State-Objects to other composables. There is just no need to do that. If you just give in "expanded: Boolean" it will also update and recompose whenever the value is changed. The State itself should be controlled by the parent.

2022-03-25 09:17 UTC, Tautellini commented on code/container/BottomAppBar.kt
> +    currentScreen: MutableState<BottomBarScreen>
See other comment, dont pass States as Parameters. 99% of the time, this is not really needed.

2022-03-25 09:22 UTC, Tautellini commented on demo/src/main/java/de/check24/compose/demo/features/bar/ComposableBottomAppBarActivity.kt
> +    currentScreen: MutableState<BottomBarScreen>
Same here.

2022-03-25 09:23 UTC, Tautellini commented on demo/src/main/java/de/check24/compose/demo/features/button/chip/AndroidUIChipActivity.kt
> +// if ChipBinding says "no reference" just: Build -> Clean Project
Thats right, but maybe dont include that as a comment here

2022-03-25 09:26 UTC, Tautellini commented on demo/src/main/java/de/check24/compose/demo/features/button/chip/ComposableChipActivity.kt
> +    Surface(
You tend to repeat the same code very often here. Didnt you make a Chip Composable? You could just provide the needed ability to control it.

2022-03-25 09:29 UTC, Tautellini commented on demo/src/main/java/de/check24/compose/demo/features/button/chip/ComposableChipGroupActivity.kt
> +                            id = R.color.gray_700
if you have not enough space for the one-liner shorthand, please use brackets.

2022-03-25 10:01 UTC, Tautellini commented on demo/src/main/java/de/check24/compose/demo/features/button/chip/ComposableChipGroupActivity.kt
> +                            end = 4.dp,
Looks like you have 8 dp of space between your items. Isnt this doable with:
horizontalArrangement = Arrangement.spacedBy(8.dp)

2022-03-25 12:55 UTC, Justus-Saringer commented on code/button/ChipGroup.kt
>                  Row(
If the row contains items like the icon and text, it aligns them nicely, so it's not only for the ripple effect. Only for a few where you have only one item😅.
I tried to do it with a box, but I don't get icon and text aligned.
Nevertheless, the button works well. I could implement it if you want it.

2022-03-25 13:13 UTC, Justus-Saringer commented on code/button/Chip.kt
> +fun ChipExample(
Good point. I looked over it again. There is one point, why I didn't include the ChipExample's chips. On the one hand, I needed some modification for the singleselection. Therefore I couldn't use the written chips. But you are completely right, that I can use my chip for the multiselection. I will make the chips more reusable.

2022-03-25 14:02 UTC, Justus-Saringer commented on code/button/Chip.kt
> +        color = if (isSelected) colorResource(id = R.color.purple_100) else colorResource(id = R.color.gray_300),
Well, now I know that we have something like that in the project :) I added the colours there and changed the resources in the code.

2022-03-25 14:13 UTC, Justus-Saringer commented on code/container/Toolbar.kt
> +    val expanded = remember { mutableStateOf(false) }
I tried to apply it but the problem is that in ComposableToolbarActivity.kt I give this property to the ShowOptionDropDown method (line 68). In this function I get an error in line 78 that val cannot be reassigned, although the property is var. I don't get the error with the =.

2022-03-25 14:48 UTC, Justus-Saringer commented on code/container/Toolbar.kt
> +fun ShowOptionDropDown(expanded: MutableState<Boolean>) {
I tried to apply it but the problem is that in ComposableToolbarActivity.kt I give this property to the ShowOptionDropDown method (line 68). In this function I get an error in line 78 that val cannot be reassigned. I don't get the error with the =. I don't understand why it behave like that.

2022-03-25 14:52 UTC, Justus-Saringer commented on demo/src/main/java/de/check24/compose/demo/features/button/chip/AndroidUIChipActivity.kt
> +// if ChipBinding says "no reference" just: Build -> Clean Project
Good to know. I changed it 👍

2022-03-25 14:56 UTC, Justus-Saringer commented on demo/src/main/java/de/check24/compose/demo/features/button/chip/ComposableChipGroupActivity.kt
> +                            id = R.color.gray_700
noted

2022-03-25 15:00 UTC, Justus-Saringer commented on demo/src/main/java/de/check24/compose/demo/features/button/chip/ComposableChipGroupActivity.kt
> +                            end = 4.dp,
I did not know that this attribute exists :D
Yes works as well. Is there an advantage with it?

2022-03-25 15:08 UTC, Justus-Saringer commented on demo/src/main/java/de/check24/compose/demo/features/button/chip/ComposableChipActivity.kt
> +    Surface(
I did this because of the padding. If you have icons in the chip you need different padding in it. Is it possible to change the padding on the fly or should I make a big chip where you can select everything via parameters?

2022-03-29 13:46 UTC, Darius3001 requested changes

2022-03-29 13:46 UTC, Darius3001 commented on demo/src/main/java/de/check24/compose/demo/features/bar/ComposableToolbarActivity.kt
> +    onDismissMenu: ((Boolean) -> Unit)? = null,
what does the boolean do?

2022-03-29 13:46 UTC, Darius3001 commented on demo/src/main/java/de/check24/compose/demo/features/button/chip/ComposableChipActivity.kt
> +    iconEnabled: Boolean
same here

2022-03-29 13:46 UTC, Darius3001 commented on demo/src/main/java/de/check24/compose/demo/features/spinner/ComposableSpinnerActivity.kt
> +        Row {
Would it also work if you leave out the box and do
```
    Row(
        modifier = Modifier.fillMaxSize(),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.Center
    ) {
        [...]
    }
```
?

2022-03-29 13:46 UTC, Darius3001 commented on demo/src/main/java/de/check24/compose/demo/theme/Color.kt
> +val purple_400 = Color(0xFF7e3ff2)
better keep camelcase `Purple400`

2022-03-31 07:05 UTC, Tautellini commented on code/button/Chip.kt
> +    value: ((String) -> String)? = null
I would propose to name the lambda like the callback you invoke it from. So in this case its "onValueChange". So the developer, using your ActionChip, actually knows what this lambda is for, without the need to read documentation.

2022-03-31 07:11 UTC, Tautellini commented on code/button/Chip.kt
> +    value: ((String) -> String)? = null
Also, why is this one unidirectional? By specifying the return type also as string, you do exactly that, you need to return a String within the Lamdba at the caller of ActionChip now.

I assume you want to return Unit here. Make sure to have a thoroughly look at this documentation: https://kotlinlang.org/docs/lambdas.html

Its a very helpful and powerful feature, which seems a little bit confusing at first, but you will love it eventually.

2022-03-31 07:17 UTC, Tautellini commented on code/button/Chip.kt
> +                fontSize = 14.sp,
This doesnt really makes sense in context of Text-Styling. You set up a style, to specify at least the font-parameters. So fontSize should be handled by MaterialTheme.typography. You normally only override bold/italic or the text-color. Since this is stuff you cannot really define a default solution for.

2022-03-31 07:19 UTC, Tautellini commented on code/container/BottomAppBar.kt
> +    currentScreen: MutableState<BottomBarScreen>
Like explained, I understand that there are scenarios where you actually might need to pass a value wrapped in a State Object as a parameter. But I still think this is not the case here. You need the state, to modify its state onClick. In a real world scenario, you would most certainly expose the onClick() as a lamdba and handle the state in the parent. You might want to think about that again, since you also changed it for the Chip itself.

2022-03-31 07:25 UTC, Tautellini commented on demo/src/main/java/de/check24/compose/demo/features/button/chip/ComposableChipActivity.kt
>          ChipExample()
You guys should go the way of having one preview for every type of composable. Be verbose, since when a developer is checking out you repo, he would assume there is a preview for every composable. Its a good practice.

It might look like overwhelmingly many boilerplate code, but it will help you in the long run in real projects. You dont always want to do a full build, sometimes you also just want to go in the interactive mode previews. Also you just need it for visualization. Previews can be grouped and named to further enhance the orga of it. If you feel like the files are getting too big, you might also want to split up Composables file by file, but not sure what was decided here.

2022-03-31 08:48 UTC, Tautellini commented on code/button/Chip.kt
> +    value: ((String) -> String)? = null
Btw you could just answer the conversation instead of editing my field haha :D 

I think we are not talking about the same thing.

If you use:

ActionChip() {
   // this here needs to return a string, back to the ActionChip
}

This is the declaration of:
() -> **String**

But you dont use that. You just call _value?.invoke(name)._ You dont expect a returning value.
This is the Declaration here:
(**_String_**) -> Unit


So you dont really want to be unidirectional here, am I right?

2022-03-31 08:56 UTC, Tautellini commented on code/button/Chip.kt
> +                        if (isSelected) value?.invoke(name)
Why you only invoke it when its selected? You should give the lambda the power to decide what it needs. So just invoke it every time the value changes. Not just when its actually selected. This way you lose deselection events.

2022-04-04 14:25 UTC, Tautellini commented on demo/src/main/java/de/check24/compose/demo/features/button/chip/ComposableChipActivity.kt
> +    icon: ImageVector? = null,
Also here, see other comment.

2022-04-04 14:26 UTC, Tautellini commented on demo/src/main/java/de/check24/compose/demo/features/button/chip/ComposableChipActivity.kt
> +    icon: ImageVector = Icons.Default.Check,
See other comment

2022-04-04 14:27 UTC, Tautellini commented on demo/src/main/java/de/check24/compose/demo/features/button/chip/ComposableChipActivity.kt
> +                    onToggle()
Why you have two different lambdas for the same clickable function?

2022-04-04 19:36 UTC, Tautellini approved these changes
LGTM. Good job :) Thanks for your effort.

2022-04-04 19:37 UTC, merged