Add google maps
kibotu/jetpack-compose-is-like-android-view pull request #2
Opened 2022-03-14 13:59 UTC by Darius3001

2022-03-14 15:06 UTC, Tautellini requested changes

2022-03-14 15:10 UTC, Tautellini commented on demo/src/main/java/de/check24/demo/features/custom/ComposableGoogleMapActivity.kt
> +    val c24Berlin = LatLng(52.51119997328961, 13.404559796099809)
Even if this is a val, I would assume you should use remember{} here. Because it will get re-created every time this composable gets recomposed.

2022-03-22 10:19 UTC, ColdTea-Projects approved these changes

2022-03-22 10:19 UTC, ColdTea-Projects commented on README.md
> +### How to apply Google Maps
nice 👍

2022-03-23 10:36 UTC, Tautellini commented on README.md
> +### How to apply Google Maps
Yeah. Nice!

2022-03-23 10:37 UTC, Tautellini approved these changes

2022-03-23 12:14 UTC, merged