Add grid
kibotu/jetpack-compose-is-like-android-view pull request #20
Opened 2022-03-25 08:40 UTC by Darius3001

2022-03-25 10:46 UTC, Tautellini commented on code/list/Grid.kt
> +fun Grid(
This is not really needed I think.

There is LazyVerticalGrid

2022-03-25 11:01 UTC, Darius3001 commented on code/list/Grid.kt
> +fun Grid(
Not exactly. You cant really enter the number exact columns & rows. I think You can play around with the sizes but that wouldnt be the same. So i made that layout (works fine with other cases btw)

2022-03-25 11:05 UTC, Darius3001 commented on code/list/Grid.kt
> +fun Grid(
It fills the screen so you would have to downsize the parent in order to get correct row- & columncount. I think this would cover more cases

2022-03-28 09:47 UTC, Tautellini commented on code/list/CustomFixedGrid.kt
> +    rowCount: Int,
I think it would make sense to include the list of items as a parameter for the fixed grid. Otherwise you may run into IndexOutOfBounds issues when not using the correct list sizes. Also what happens if you have more items, than the set up 2x2  Grid? 
It would be pretty easy to make this example also dynamic. You could check for the needed rows by making a modulo check on the list size. 

e.g. 
list.size / columnCount = rowCount without Rest
if(list.size % columnCount != 0) rowCount = rowCount + 1

Now your grid would be dynamic, based on the count of items. It depends on what you wanna achieve with this, but it would be a nice feature.

2022-03-28 09:51 UTC, Tautellini commented on demo/src/main/java/de/check24/compose/demo/features/list/grid/ComposableGridActivity.kt
> +                        Box(
It seems like this Box is a redundant layout.
When looking into the Surface() Implementation, you can see that you are in the Scope of a Surface, as well als the ScaffoldLayout. I think there is no need to wrap this inside a new parent layout. Think about it like the <merge> tag in XML resources.

When you just want the column to fill the max size, give the modifier to the Column directly. Content Alignment can also be done inside of the Column.

2022-03-28 11:39 UTC, Darius3001 commented on code/list/CustomFixedGrid.kt
> +    rowCount: Int,
i dont think it makes sense to have items that are composables in a list in a layout. To count the items you can also do measurables.size or placeables.size

Well it works with less elements but not for more. 
Since the xml version is also dynamic that would make sense. Gonna change it.
rowCount as parameter would be redundant tho so i would remove that

2022-03-28 11:41 UTC, Darius3001 commented on demo/src/main/java/de/check24/compose/demo/features/list/grid/ComposableGridActivity.kt
> +                        Box(
Yes true. Changing it

2022-03-28 11:59 UTC, Tautellini commented on demo/src/main/java/de/check24/compose/demo/features/list/grid/ComposableGridActivity.kt
> +                            Spacer(modifier = Modifier.size(100.dp))
Minor thing: Semantically spoken, the spacer only occupies height or width in this case. So its better to use Modifier.height() or Modifier.width() to make it 100% clear what this spacer is used for.

2022-03-28 12:02 UTC, Tautellini commented on demo/src/main/java/de/check24/compose/demo/features/list/grid/ComposableGridActivity.kt
> +                        Card(
Normally a card should have content. If it has some content and the Composable only accepts one type of compose scoped content, you should write it behind the round brackets.

e.g.
Card(parameters) {}

2022-03-28 13:37 UTC, Tautellini commented on code/list/Grid.kt
> +    Box(Modifier.size(200.dp)) {
Box is redundant I think.

2022-03-28 13:37 UTC, Tautellini commented on demo/src/main/java/de/check24/compose/demo/features/list/grid/ComposableGridActivity.kt
> +    Box(Modifier.size(200.dp)) {
Also here.

2022-03-28 13:48 UTC, Tautellini commented on demo/src/main/java/de/check24/compose/demo/features/list/grid/CustomFixedGrid.kt
> +        val positions: MutableMap<Placeable, IntOffset> = mutableMapOf()
Line 81 to 103 can be replaced by:

` layout(
            width = layoutWidth,
            height = layoutHeight
        ) {
            placeables.forEachIndexed { index, placeable ->
                placeable.place(
                    IntOffset(
                        x = xPositions[index % columnCount],
                        y = yPositions[index / columnCount]
                    )
                )
            }
        }`

2022-03-28 13:50 UTC, Tautellini commented on demo/src/main/java/de/check24/compose/demo/features/list/grid/CustomFixedGrid.kt
> +    for (i in heights.indices step columnCount) {
Can you explain, why we only do it by the step of columnCount? Dont you just measure the last one this way?

2022-03-29 07:57 UTC, Darius3001 commented on demo/src/main/java/de/check24/compose/demo/features/list/grid/CustomFixedGrid.kt
> +    for (i in heights.indices step columnCount) {
i think you overlooked the inner for loop. it goes from the current i until i+columnCount (unless the row is not completely filled. thats where the min() comes in handy)

2022-03-29 08:07 UTC, Darius3001 commented on demo/src/main/java/de/check24/compose/demo/features/list/grid/CustomFixedGrid.kt
> +        val positions: MutableMap<Placeable, IntOffset> = mutableMapOf()
works

2022-03-29 11:57 UTC, Justus-Saringer requested changes

2022-03-29 11:57 UTC, Justus-Saringer commented on demo/src/main/java/de/check24/compose/demo/features/list/grid/CustomFixedGrid.kt
> +import androidx.compose.runtime.Composable
Could you remove the unnecessary imports?

2022-03-29 11:57 UTC, Justus-Saringer commented on demo/src/main/java/de/check24/compose/demo/features/list/grid/CustomFixedGrid.kt
> +        Color(0xFFBB86FC),
You could add your colours to the theme>Color.kt file. Then everyone in the project can use them.

2022-03-29 11:57 UTC, Justus-Saringer commented on demo/src/main/java/de/check24/compose/demo/features/list/grid/CustomFixedGrid.kt
> +        val rowCount: Int = measurables.size / columnCount
I think if you use an odd number your code will break.

2022-03-29 12:06 UTC, Justus-Saringer approved these changes
Good work

2022-03-29 12:07 UTC, merged