Add flow
kibotu/jetpack-compose-is-like-android-view pull request #31
Opened 2022-03-30 12:34 UTC by Justus-Saringer

2022-03-31 07:34 UTC, Tautellini commented on demo/src/main/java/de/check24/compose/demo/features/positioning/ComposableFlowActivity.kt
> +private fun TextViews() {
This looks very complicated :D 
Just as a different perspective, becauce since its compose:
Why not just having one Composable for the Text, which accepts a text, and write it ten times then? Not really much more code, but much better to read.

2022-03-31 08:43 UTC, Tautellini commented on demo/src/main/java/de/check24/compose/demo/features/positioning/ComposableFlowActivity.kt
> +    ConstraintLayout(
Looks like this ConstraintLayout is serving the same purpose as a simple Column. Would propose to use Column when the layout is easy enough.

2022-03-31 08:43 UTC, Tautellini requested changes
see comments

2022-03-31 09:51 UTC, Justus-Saringer commented on demo/src/main/java/de/check24/compose/demo/features/positioning/ComposableFlowActivity.kt
> +private fun TextViews() {
I made it a little bit more compact with using a forEach-loop on the textList. I will delete the different colours, to get it more compact.

2022-03-31 09:55 UTC, Justus-Saringer commented on demo/src/main/java/de/check24/compose/demo/features/positioning/ComposableFlowActivity.kt
> +    ConstraintLayout(
I tried it yesterday and it didn't work, but now it works.

2022-04-04 19:49 UTC, Tautellini commented on demo/src/main/java/de/check24/compose/demo/features/positioning/ComposableFlowActivity.kt
> +private fun TextViews() {
Its not about it being more compact. Please dont see it that way.

Clean code is most of the time about a good readability. Because you will read other code much more, than you will ever write yourself. So you can as well make yourself have a good time. While this is a very simple example, and this is totally fine, I see the possibility for you to learn a better perspective.

Imagine:
MyText("one", Color.Red)
MyText("two", Color.Blue)
MyText("three", Color.Cyan)
MyText("four", Color.Black)
MyText("five", Color.White)
MyText("six", Color.Green)
MyText("seven", Color.Whatever)


This is not really a worse approach, but much easier to read. Just want you to be aware of the fact, that sometimes, the easiest way, is still a good way of doing things in terms of readability. I like the KISS prinicple. And you dont lose anything by it most of the time.

2022-04-04 19:52 UTC, Tautellini approved these changes
lgtm :)

2022-04-05 07:35 UTC, Justus-Saringer commented on demo/src/main/java/de/check24/compose/demo/features/positioning/ComposableFlowActivity.kt
> +private fun TextViews() {
Thanks for the comment. I noted it down in Notion in my Knowledge chapter :)

2022-04-05 07:35 UTC, merged