Image button
kibotu/jetpack-compose-is-like-android-view pull request #33
Opened 2022-03-07 17:11 UTC by Darius3001

2022-03-07 17:32 UTC, Stallinator commented on code/button/ImageButton.xml
> +    app:srcCompat="@drawable/c24logo"
include the glide stuff here :)

2022-03-07 17:32 UTC, Stallinator commented on demo/src/main/java/de/check24/demo/features/button/ComposableImageButtonActivity.kt
> +        modifier = Modifier.size(240.dp)
lets look for better fix for ripple effect here

2022-03-07 17:33 UTC, Stallinator requested changes
see comments

2022-03-07 22:33 UTC, Tautellini commented on demo/src/main/java/de/check24/demo/features/button/ComposableImageButtonActivity.kt
> +        Image(
While this works, an IconButton is supposed to have an Icon as Composable Content.

2022-03-07 22:35 UTC, Tautellini commented on demo/src/main/java/de/check24/demo/features/button/AndroidUIImageButtonActivity.kt
> +        val imageView = findViewById<android.widget.ImageButton>(R.id.imageButton)
Im not sure what we decided for the demo project, but this should be done the compose/hybrid way. We have a glide example in our internal code base.

2022-03-09 10:31 UTC, Stallinator commented on code/button/ImageButton.xml
> +    app:srcCompat="@drawable/c24logo"
remove the srcCompat line pls

2022-03-09 10:31 UTC, Stallinator commented on demo/src/main/res/layout/image_button.xml
> +        app:srcCompat="@drawable/c24logo" />
remove the src compat line

2022-03-09 10:59 UTC, Stallinator approved these changes

2022-03-09 11:00 UTC, merged