Add ViewModel
kibotu/jetpack-compose-is-like-android-view pull request #40
Opened 2022-04-05 11:23 UTC by Justus-Saringer

2022-04-05 11:34 UTC, ColdTea-Projects requested changes

2022-04-05 11:34 UTC, ColdTea-Projects commented on code/states/ViewModel.kt
> +class MyViewModel : IMyViewModel {
Please try not to use prefixes such as I , those are not part of kotlin naming conventions. You can simply write MyViewModelInterface, or BaseMyViewModel etc. But please use a full name

2022-04-05 11:34 UTC, ColdTea-Projects commented on code/states/ViewModel.kt
> +class MyViewModel : IMyViewModel {
Or in some cases: 
interface MyViewModel()
class MyViewModelImpl()

2022-04-05 11:44 UTC, Justus-Saringer commented on code/states/ViewModel.kt
> +class MyViewModel : IMyViewModel {
Thank you :)

2022-04-07 09:41 UTC, Tautellini commented on code/states/ViewModel.kt
> +    fun onClick()
Im confused about the naming of those functions. In the viewModel actual methods should be used, to do something. Lets say you want to start a refreshing call after onClick, this is what should live in the viewModel. Starting the actual business logic.

I would propose to not make callbacks directly to the viewModel, but have one more layer of abstraction. Callbacks should be send to its parent composable. There you just call the viewModel to do your stuff.

In this example, you could as well just not have any function in the viewModel at all.

2022-04-07 09:42 UTC, Tautellini commented on code/states/ViewModel.kt
> +fun MyScreen(myViewModelInterface: MyViewModelInterface) {
The Interface is a Type of your object. Your object itself should not be named Interface. Just call it viewModel.

2022-04-07 09:43 UTC, Tautellini commented on code/states/ViewModel.kt
> +private fun ViewModelExamplePreview() {
Your naming is inconsistent. Your composable is named: MyScreen.
So in this case, the Preview should be: MyScreenPreview. Please check what you want to have.

2022-04-07 09:46 UTC, Tautellini commented on code/states/ViewModel.xml
> +    fun onToggle() {
Same here, I dont really like this example, because normally you would have one more layer of abstraction, instead of just doing callbacks directly to the viewModel. Please name the methods accordingly to what should be done in the viewModel. You normally dont send just a callback to the viewModel.

2022-04-07 09:48 UTC, Tautellini requested changes
Small comments

2022-04-07 12:42 UTC, Justus-Saringer commented on code/states/ViewModel.kt
> +    fun onClick()
Alright, I changed the name from onClick to addNumber and onToggle to toggle. I just wanted to show how one uses functions in a compose viewModel. Furthermore I didn't want to have viewModel, which only holds states.  Nevertheless, if you want them out of it, I can remove the functions.

2022-04-07 12:52 UTC, Justus-Saringer commented on code/states/ViewModel.kt
> +private fun ViewModelExamplePreview() {
You are right.

2022-04-07 13:14 UTC, Justus-Saringer commented on code/states/ViewModel.xml
> +    fun onToggle() {
Can you send me a link, where I can learn more about that abstraction layer?

2022-04-08 07:21 UTC, Darius3001 commented on demo/src/main/java/de/check24/compose/demo/features/viewmodel/AndroidUIViewModelActivity.kt
> +class MyAndroidViewViewModel : ViewModel() {
Maybe rename: "MyAndroidUIViewModel"

2022-04-08 07:26 UTC, Darius3001 commented on demo/src/main/java/de/check24/compose/demo/features/viewmodel/ComposableViewModelActivity.kt
> +fun MyScreen(myViewModel: MyViewModel = viewModel()) {
why do you use a default parameter?

2022-04-08 07:28 UTC, Darius3001 commented on demo/src/main/java/de/check24/compose/demo/features/viewmodel/AndroidUIViewModelActivity.kt
> +    private var binding: ViewmodelBinding? = null
Small thing but keep the camelcase maybe

2022-04-08 07:42 UTC, Darius3001 commented on demo/src/main/java/de/check24/compose/demo/features/viewmodel/AndroidUIViewModelActivity.kt
> +        binding?.textView?.text = viewModel.number.toString()
Not necessary but always fancy using let and apply (also a fancier null check)
```
binding?.apply {

    setBackgroundColor(viewModel.isClicked, boxView)

    textView.text = viewModel.number.toString()

    viewModelSwitch.setOnClickListener {
        viewModel.onToggle()
        setBackgroundColor(viewModel.isClicked, boxView)
    }

    textView.setOnClickListener {
        viewModel.onClick()
        textView.text = viewModel.number.toString()
    }
}
```

2022-04-08 07:56 UTC, Justus-Saringer commented on demo/src/main/java/de/check24/compose/demo/features/viewmodel/AndroidUIViewModelActivity.kt
> +class MyAndroidViewViewModel : ViewModel() {
Good point.

2022-04-08 07:58 UTC, Darius3001 commented on demo/src/main/java/de/check24/compose/demo/features/viewmodel/ComposableViewModelActivity.kt
> +fun MyScreen(myViewModel: MyViewModel = viewModel()) {
i believe if u use functions from your interface it wouldnt work because theyre not defined in viewModel()

2022-04-08 08:03 UTC, Darius3001 commented on demo/src/main/java/de/check24/compose/demo/features/viewmodel/ComposableViewModelActivity.kt
> +        val myViewModel = object : MyViewModelInterface {
Why dont you do it like in the on create method (by viewmodels <...)

2022-04-08 08:05 UTC, Justus-Saringer commented on demo/src/main/java/de/check24/compose/demo/features/viewmodel/ComposableViewModelActivity.kt
> +fun MyScreen(myViewModel: MyViewModel = viewModel()) {
I have to admit. I don't know. I removed it.

2022-04-08 08:06 UTC, Darius3001 commented on demo/src/main/java/de/check24/compose/demo/features/viewmodel/ComposableViewModelActivity.kt
> +                    .clickable { myViewModel.addNumber() },
if you do the box clickable instead the ripple effect would be nicer

2022-04-08 08:08 UTC, Justus-Saringer commented on demo/src/main/java/de/check24/compose/demo/features/viewmodel/AndroidUIViewModelActivity.kt
> +    private var binding: ViewmodelBinding? = null
Thanks, I didn't see that. Nevertheless this file is autogenerated through Android Studio. It is generated for the viewBinding part. As a consequence I cannot rename it, at least I guess.

2022-04-08 08:08 UTC, Darius3001 commented on demo/src/main/res/layout/viewmodel.xml
> +        android:background="@color/blue_200"
add this to add ripple effect
`android:foreground="?attr/selectableItemBackground"`

2022-04-08 08:12 UTC, Justus-Saringer commented on demo/src/main/java/de/check24/compose/demo/features/viewmodel/AndroidUIViewModelActivity.kt
> +        binding?.textView?.text = viewModel.number.toString()
I changed it. Your way looks way better! Big thanks. I forgot that I can use it.

2022-04-08 08:19 UTC, Justus-Saringer commented on demo/src/main/java/de/check24/compose/demo/features/viewmodel/ComposableViewModelActivity.kt
> +        val myViewModel = object : MyViewModelInterface {
Because it is an Interface. Therefore I must override and create the attributes and functions of the Interface. Furthermore it's just for the Preview.
Only for understanding, I implemented the viewModel twice. One way is the the way how Google recommends it and the other way is with creating an Interface. The difference between these two is, that with Google's way the preview doesn't work. With the Interface the preview works fine. 
I used the composable without the interface for the app.

2022-04-08 08:27 UTC, Justus-Saringer commented on demo/src/main/java/de/check24/compose/demo/features/viewmodel/ComposableViewModelActivity.kt
> +                    .clickable { myViewModel.addNumber() },
Very good point!

2022-04-08 08:27 UTC, Justus-Saringer commented on demo/src/main/res/layout/viewmodel.xml
> +        android:background="@color/blue_200"
Nice suggestion. I implemented it immediately.

2022-04-08 11:12 UTC, Darius3001 commented on demo/src/main/java/de/check24/compose/demo/features/viewmodel/AndroidUIViewModelActivity.kt
> +    private var binding: ViewmodelBinding? = null
Ah okay then its fine

2022-04-08 11:24 UTC, Darius3001 commented on demo/src/main/java/de/check24/compose/demo/features/viewmodel/ComposableViewModelActivity.kt
> +        val myViewModel = object : MyViewModelInterface {
`val myViewModel = MyViewModel()` works as well. Writing twice would be redundant

2022-04-08 13:07 UTC, Darius3001 commented on code/states/ViewModel.xml
> +        binding?.textView?.text = viewModel.number.toString()
needs update

2022-04-08 13:08 UTC, Darius3001 commented on code/states/ViewModel.kt
> +@Preview(showBackground = true, showSystemUi = true, device = Devices.PIXEL_4)
remove preview out of website i would say

2022-04-08 13:10 UTC, Darius3001 commented on code/states/ViewModel.xml
> +class MyAndroidUIViewViewModel : ViewModel() {
MyAndroidUIViewModel instead of MyAndroidUIViewViewModel

2022-04-08 13:10 UTC, Darius3001 commented on demo/src/main/java/de/check24/compose/demo/features/viewmodel/AndroidUIViewModelActivity.kt
> +class MyAndroidUIViewViewModel : ViewModel() {
MyAndroidUIViewModel instead of MyAndroidUIViewViewModel as well

2022-04-08 13:12 UTC, Darius3001 commented on index.cirru
> +        .card (.lang Kotlin) $ pre.code $ code (@insert code/states/BundleObjects.kt)
you forgot to remove this

2022-04-08 13:29 UTC, Justus-Saringer commented on code/states/ViewModel.kt
> +@Preview(showBackground = true, showSystemUi = true, device = Devices.PIXEL_4)
Oh yes, thank you.

2022-04-08 13:37 UTC, Justus-Saringer commented on index.cirru
> +        .card (.lang Kotlin) $ pre.code $ code (@insert code/states/BundleObjects.kt)
Oh right, thank you very much!

2022-04-08 13:43 UTC, Darius3001 approved these changes

2022-04-08 13:46 UTC, merged