Add bundle objects
kibotu/jetpack-compose-is-like-android-view pull request #43
Opened 2022-04-06 13:54 UTC by Justus-Saringer

2022-04-07 09:52 UTC, Tautellini commented on code/states/BundleObjects.kt
> +private fun RiverText(river: MutableState<River>) {
You dont modify the state of river here. So please dont pass the state itself. Also if you would need to, please favor a lambda wherever possible. Also this is a suboptimal naming right? You dont know at this point you are talking about a ListSaver.

2022-04-07 09:54 UTC, Tautellini requested changes
see comments

2022-04-07 13:56 UTC, Justus-Saringer commented on code/states/BundleObjects.kt
> +private fun RiverText(river: MutableState<River>) {
I adopted the comment. I know the naming is not on top of the world, but I don't know how to do it better. I tried to improve it.

2022-04-08 08:46 UTC, Darius3001 requested changes

2022-04-08 08:46 UTC, Darius3001 commented on demo/src/main/java/de/check24/compose/demo/features/bundle/AndroidUIBundleObjectsActivity.kt
> +        binding?.textView3?.text = river2
still a fan of apply 😄

2022-04-08 08:46 UTC, Darius3001 commented on demo/src/main/java/de/check24/compose/demo/features/bundle/AndroidUIBundleObjectsActivity.kt
> +
you dont really use bundle. We should rethink that and also maybe another example.

2022-04-08 12:40 UTC, closed without merging