Add sideeffect
kibotu/jetpack-compose-is-like-android-view pull request #54
Opened 2022-04-12 14:22 UTC by Justus-Saringer

2022-04-12 14:55 UTC, Darius3001 requested changes

2022-04-12 14:55 UTC, Darius3001 commented on code/sideeffects/SideEffect.kt
> +
could you maybe add a comment what problem will occur

2022-04-12 14:55 UTC, Darius3001 commented on code/sideeffects/SideEffect.kt
> +    SideEffect {
A lil comment on what it does. mustnt be to long

2022-04-12 14:55 UTC, Darius3001 commented on demo/src/main/java/de/check24/compose/demo/features/sideeffects/ComposableSideEffectActivity.kt
> +    Thread.sleep(1000)
you can also apply the comments in the demo

2022-04-12 15:51 UTC, Justus-Saringer commented on demo/src/main/java/de/check24/compose/demo/features/sideeffects/ComposableSideEffectActivity.kt
> +    Thread.sleep(1000)
I added comments to both parts

2022-04-13 07:28 UTC, Darius3001 approved these changes

2022-04-13 07:29 UTC, merged