Add spinner
kibotu/jetpack-compose-is-like-android-view pull request #9
Opened 2022-03-16 12:03 UTC by Justus-Saringer

2022-03-16 15:49 UTC, ColdTea-Projects requested changes

2022-03-16 15:49 UTC, ColdTea-Projects commented on code/container/Spinner.kt
> +            .fillMaxWidth()
.fillMaxSize()

2022-03-16 15:49 UTC, ColdTea-Projects commented on demo/src/main/java/de/check24/compose/demo/features/spinner/ComposableSpinnerActivity.kt
> +            .fillMaxWidth()
.fillMaxSize()

2022-03-16 15:49 UTC, ColdTea-Projects commented on demo/src/main/java/de/check24/compose/demo/features/spinner/ComposableSpinnerActivity.kt
> +private fun SpinnerExample() {
you already have a file Spinner.kt which has the same code block. Why do not you use that composable function instead of rewriting everything?

2022-03-17 11:53 UTC, Justus-Saringer commented on demo/src/main/java/de/check24/compose/demo/features/spinner/ComposableSpinnerActivity.kt
> +private fun SpinnerExample() {
The Spinner.kt file is for the website. Everything what is in there is displayed on the website part.

2022-03-18 13:01 UTC, ColdTea-Projects approved these changes

2022-03-18 13:02 UTC, merged